#+TITLE Local Custimizations for Starter Kit
#+PROPERTY: header-args :results silent

* Set External Programs

#+BEGIN_SRC emacs-lisp
(setq ispell-program-name "aspell")
#+END_SRC

* Window Configuration

#+BEGIN_SRC emacs-lisp
  (when window-system
    (tool-bar-mode -1)
    (setq initial-frame-alist
          '((top . 0) ; (left . 180)
            (width . 100) (height . 54))))
#+END_SRC

* Global Key Bindings

We set up some key bindings that are useful across modes.  Currently
only ~F12~ is bound to ~compile~.

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<f12>") 'compile)
#+END_SRC

* Customize Ido Mode

#+BEGIN_SRC emacs-lisp
  (setq ido-use-filename-at-point 'guess)
  (setq ido-file-extensions-order
        '(".org"
          "*.jl" "*.lisp" "*.el" "*.rs"
          "*.h" "*.cpp" "*.c" ".el"
          "*.md" "*.rst" ".tex" ".text" ".txt"
          "*.bib" ".log" "*.bbl"))
  (setq ido-use-virtual-buffers t)
#+END_SRC

* Load Some Additional Starter-Kit Files

#+BEGIN_SRC emacs-lisp
  (starter-kit-load "eshell")
  (starter-kit-load "js")
  (starter-kit-load "lisp")
  (starter-kit-load "org")
#+END_SRC

* Julia

Julia works rather well with ESS, but the default writer chokes on
code blocks that don't end with an iterable.  Therefore we override
the command to write objects.  The ~trywritecsv~ function has to be
defined in the =~/.juliarc.js= file, e.g., using the following
definition:

#+BEGIN_SRC julia :tangle no :eval never
function trywritecsv(io, a; opts...)
    try writecsv(io, a; opts...)
    catch open(io, "w") do stream
              write(stream, "")
          end
    end
end;
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (load (expand-file-name "~/Prog/Julia/Emacs/Ess/lisp/ess-site.el"))
  (add-to-list 'load-path
               (expand-file-name "~/Prog/Julia/Emacs/Ob-Julia"))
  (setq inferior-julia-program-name "julia")
  (setq inferior-julia-args "-q --color=no")
  (load (expand-file-name "~/Prog/Julia/Emacs/Ob-Julia/ob-julia.el"))
  (setq org-babel-julia-write-object-command "trywritecsv(\"%s\",%s)")
#+END_SRC

* Rust

#+BEGIN_SRC emacs-lisp
  (starter-kit-install-if-needed 'rust-mode)
  (add-hook 'rust-mode-hook
            (lambda ()
              (set (make-local-variable 'compile-command) "cargo run")))
#+END_SRC

* Clojure

Ensure that ~clojure-mode~ and ~cider~ are present.  Since multiple
versions of cider are present in the repositories it may be necessary
to install the desired version manually.

#+BEGIN_SRC emacs-lisp
  (starter-kit-install-if-needed 'clojure-mode)
  (starter-kit-install-if-needed 'cider)
#+END_SRC

* Customize Org Mode

This section assumes that the path to =ob-julia.el= has already been
set.

#+BEGIN_SRC emacs-lisp
  (setq org-confirm-babel-evaluate nil)
  (add-hook 'org-babel-after-execute-hook
            'org-display-inline-images)
  (add-hook 'org-mode-hook
            'org-display-inline-images)
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp t) (julia . t)))
#+END_SRC
